export const INITIAL_MAIN_SCREEN = `INITIAL_MAIN_SCREEN`;
export const REFRESHING_TOPICS = `REFRESH_TOPICS`;

export const GET_TOPICS_SUCCESS = `GET_TOPICS_SUCCESS`;
export const GET_GENES_SUCCESS = `GET_GENES_SUCCESS`;

export const TOPIC_IS_LOADING_MORE = `TOPIC_IS_LOADING_MORE`;
export const TOPIC_IS_REFRESHING = `TOPIC_IS_REFRESHING`;

export const GENE_IS_REFRESHING = `GENE_IS_REFRESHING`;
export const GENE_IS_LOADINGD_MORE = `GENE_IS_LOADINGD_MORE`;

export const CHANGE_SEGMENTED_INDEX = `CHANGE_SEGMENTED_INDEX`;

export const INCREASE_TOPIC_PAGE_NUMBER = `INCREASE_TOPIC_PAGE_NUMBER`;
