export const INITIAL_MAIN_SCREEN = `INITIAL_MAIN_SCREEN`;
export const REFRESHING_TOPICS = `REFRESH_TOPICS`;

export const GET_TOPICS_SUCCESS = `GET_TOPICS_SUCCESS`;

export const IS_LOAD_MORE = `IS_LOAD_MORE`;
export const IS_REFRESHING = `IS_REFRESHING`;

export const CHANGE_SEGMENTED_INDEX = `CHANGE_SEGMENTED_INDEX`;

export const INCREASE_TOPIC_PAGE_NUMBER = `INCREASE_TOPIC_PAGE_NUMBER`;
