
export const GET_TOPICS_SUCCESS = `GET_TOPICS_SUCCESS`;
export const GET_GENES_SUCCESS = `GET_GENES_SUCCESS`;

export const CHANGE_COMMUNITY_TYPE = `CHANGE_COMMUNITY_TYPE`;
export const TOPIC_IS_LOADING_MORE = `TOPIC_IS_LOADING_MORE`;
export const TOPIC_IS_REFRESHING = `TOPIC_IS_REFRESHING`;

export const CHANGE_GENE_TYPE = `CHANGE_GENE_TYPE`;
export const GENE_IS_REFRESHING = `GENE_IS_REFRESHING`;
export const GENE_IS_LOADINGD_MORE = `GENE_IS_LOADINGD_MORE`;

export const CHANGE_SEGMENTED_INDEX = `CHANGE_SEGMENTED_INDEX`;

