
export const GET_TOPICS_SUCCESS = `GET_TOPICS_SUCCESS`
export const GET_TOPICS_ERROR = `GET_TOPICS_ERROR`
export const GET_GENES_SUCCESS = `GET_GENES_SUCCESS`
export const GET_GENES_ERROR = `GET_GENES_ERROR`
export const GET_BATTLES_SUCCESS = `GET_BATTLES_SUCCESS`
export const GET_BATTLES_ERROR = `GET_BATTLES_ERROR`

export const CHANGE_COMMUNITY_TYPE = `CHANGE_COMMUNITY_TYPE`
export const TOPIC_IS_LOADING_MORE = `TOPIC_IS_LOADING_MORE`
export const TOPIC_IS_REFRESHING = `TOPIC_IS_REFRESHING`

export const BATTLE_IS_REFRESHING = `BATTLE_IS_REFRESHING`

export const CHANGE_GENE_TYPE = `CHANGE_GENE_TYPE`
export const GENE_IS_REFRESHING = `GENE_IS_REFRESHING`
export const GENE_IS_LOADINGD_MORE = `GENE_IS_LOADINGD_MORE`

export const CHANGE_SEGMENTED_INDEX = `CHANGE_SEGMENTED_INDEX`
export const CHANGE_SCROLL_TYPE = `CHANGE_SCROLL_TYPE`

export const GET_QAS_SUCCESS = `GET_QAS_SUCCESS`
export const GET_QAS_ERROR = `GET_QAS_ERROR`

export const GET_GAMES_SUCCESS = `GET_GAMES_SUCCESS`
export const GET_GAMES_ERROR = `GET_GAMES_ERROR`

export const GET_RANK_SUCCESS = `GET_RANK_SUCCESS`
export const GET_RANK_ERROR = `GET_RANK_ERROR`

export const GET_CIRCLE_SUCCESS = `GET_CIRCLE_SUCCESS`
export const GET_CIRCLE_ERROR = `GET_CIRCLE_ERROR`

export const GET_STORE_SUCCESS = `GET_STORE_SUCCESS`
export const GET_STORE_ERROR = `GET_STORE_ERROR`

export const GET_TRADE_SUCCESS = `GET_TRADE_SUCCESS`
export const GET_TRADE_ERROR = `GET_TRADE_ERROR`

export const GET_RECOMMEND_SUCCESS = `GET_RECOMMEND_SUCCESS`
export const GET_RECOMMEND_ERROR = `GET_RECOMMEND_ERROR`

export const GET_DISCOUNT_SUCCESS = `GET_DISCOUNT_SUCCESS`
export const GET_DISCOUNT_ERROR = `GET_DISCOUNT_ERROR`

export const CHANGE_CIRCLE_TYPE = `CHANGE_CIRCLE_TYPE`
export const GET_TOPICS_RECOMMEND_SUCCESS = `GET_TOPICS_RECOMMEND_SUCCESS`